SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `ewa` DEFAULT CHARACTER SET ascii COLLATE ascii_bin;
USE `ewa`;

CREATE TABLE IF NOT EXISTS `dns_cache` (
  `ip_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `host` varchar(256) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `type` enum('ip','host') CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `update_date` datetime NOT NULL,
  PRIMARY KEY (`ip_id`),
  UNIQUE KEY `HOST` (`host`)
) ENGINE=InnoDB DEFAULT CHARSET=armscii8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
